import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import {
  MicrophoneIcon,
  SearchIcon,
  ViewGridIcon,
} from "@heroicons/react/outline";
import Avatar from "../components/Avatar";
import Image from "next/image";
import Footer from "../components/Footer";
import { useRef } from "react";
import { useRouter } from "next/router";

export default function Home() {
  const { data: session, status } = useSession();
  const loading = status === "loading";
  const router = useRouter();
  // always use a const until you need a let
  //const let var (never use var ) always use let before bar, const first, let is for changing values
  const searchInputRef = useRef(null);

  const search = (e) => {
    e.preventDefault();
    const term = searchInputRef.current.value;

    if (!term) return;
    //push the history
    router.push(`/search?term=${term}`);
  };
  return (
    <>
      {!session && (
        <>
          <div className="flex flex-col items-center justify-center h-screen">
            <Image
              className="animate-pulse"
              src="https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_92x30dp.png"
              width="200"
              height="80"
              alt="Google Image"
            />
            <div className="flex justify-center mt-5 ">
              <button
                className="bg-blue-700 p-4 w-full rounded-lg text-white font-bold text-lg "
                href={`/api/auth/signin`}
                onClick={(e) => {
                  e.preventDefault();
                  signIn();
                }}
              >
                Sign In
              </button>
            </div>
          </div>
        </>
      )}

      {session && (
        <>
          <div className="flex flex-col items-center justify-center h-screen">
            <Head>
              <title>Google 3.0</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>

            <header className="flex w-full pl-2 h-20 justify-between text-sm text-gray-700">
              <div className="flex space-x-4 items-center">
                <a href="#" className="link font-semibold">
                  About
                </a>
                <a href="#" className="link font-semibold">
                  Store
                </a>
              </div>

              <div className="flex space-x-4 items-center">
                <a href="#" className="link">
                  Gmail
                </a>
                <a href="#" className="link">
                  Images
                </a>

                <ViewGridIcon className="h-10 w-10 p-2 cursor-pointer rounded-full hover:bg-gray-100" />

                <Avatar url="https://img.search.brave.com/pg0Br7D51MtQxTC9u4v7k-vOSV0sgPwNu4grIEN7zk0/rs:fit:844:225:1/g:ce/aHR0cHM6Ly90c2Uz/Lm1tLmJpbmcubmV0/L3RoP2lkPU9JUC5a/NVRpU0xadzdaSUFQ/YnB4MXJLclF3SGFF/SyZwaWQ9QXBp" />
              </div>
            </header>

            <form
              action=""
              className="flex flex-col items-center mt-32 flex-grow w-4/5"
            >
              <Image
                src="https://www.google.com/logos/doodles/2022/winter-games-2022-begin-feb-4-6753651837109353.5-law.gif"
                width="400"
                height="200"
                alt="Search Image"
              />
              <div
                className="flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg rounded-full border-2 border-gray-200 px-5 py-3 items-center max-w-md sm:max-w-xl lg:max-w-2xl"
              >
                <SearchIcon className="h-5 mr-3 text-gray-500 cursor-pointer transition duration-150 transform hover:scale-110" />
                <input
                  ref={searchInputRef}
                  type="text"
                  className="flex-grow focus:outline-none "
                />
                <MicrophoneIcon className="h-5 text-gray-500 cursor-pointer duration-150 transform hover:scale-110" />
              </div>
              <div className="flex flex-col w-1/2 space-y-2 justify-center m-8 sm:space-y-0 sm:flex-row sm:space-x-4">
                <button onClick={search} className="btn">
                  Google Search
                </button>

                <button onClick={search} className="btn">
                  I'm Feeling Lucky
                </button>
              </div>
            </form>

            <Footer />
          </div>
        </>
      )}
    </>
  );
}
